// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhVCCjD4QkYBWHwhoiRRvhY68dxX9RH6o',
    appId: '1:1074759976733:web:818c0875fb51bb0dfd43f4',
    messagingSenderId: '1074759976733',
    projectId: 'daily-journal-c9745',
    authDomain: 'daily-journal-c9745.firebaseapp.com',
    storageBucket: 'daily-journal-c9745.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaCg1wwtZqa4hh23qUcA7l9X6oMveC2Aw',
    appId: '1:1074759976733:android:160ce8dddb18101cfd43f4',
    messagingSenderId: '1074759976733',
    projectId: 'daily-journal-c9745',
    storageBucket: 'daily-journal-c9745.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhVCCjD4QkYBWHwhoiRRvhY68dxX9RH6o',
    appId: '1:1074759976733:web:9a26e1e9e047e6befd43f4',
    messagingSenderId: '1074759976733',
    projectId: 'daily-journal-c9745',
    authDomain: 'daily-journal-c9745.firebaseapp.com',
    storageBucket: 'daily-journal-c9745.firebasestorage.app',
  );

}